name: 'Automate GitHub Projects'
description: 'Automate GitHub Projects'
author: 'Stanley Ndagi <ndagis@gmail.com>'
inputs:
  token:
    description: 'GitHub token'
    required: true
  project_url:
    description: 'Project URL'
    required: true
  column:
    description: 'Column name'
    required: false
    default: 'To do'
  action:
    description: 'Action to be done'
    required: false
    default: 'update'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'git-pull-request'
  color: 'purple'
